stages:
  - test
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  ALLURE_RESULTS: "target/allure-results"
  PLAYWRIGHT_BROWSERS_PATH: "0"

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  image: maven:3.8.6-openjdk-17
  before_script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install playwright
    - playwright install --with-deps
  script:
    - mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS
    expire_in: 1 week

allure-report:
  stage: report
  image: maven:3.8.6-openjdk-17
  script:
    - mvn allure:report
  artifacts:
    paths:
      - target/site/allure-maven-plugin/
    expire_in: 1 week
  only:
    - merge_requests
    - master

pages:
  stage: report
  image: alpine:latest
  script:
    - mkdir -p public
    - cp -r target/site/allure-maven-plugin/* public/
  artifacts:
    paths:
      - public
  only:
    - master