name: Run Automated Tests

on:
  pull_request:
    branches: [ master ]  # Тесты запустятся при PR в master
  workflow_dispatch:     # Позволит запускать тесты вручную через UI GitHub

jobs:
  test:
    runs-on: ubuntu-latest   # ОС для запуска тестов

    steps:
      # Шаг 1: Загружаем код из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Кэшируем зависимости Maven для ускорения

      # Шаг 3: Запускаем тесты через Maven
      - name: Run Tests
        run: mvn clean test

      # (Опционально) Генерируем Allure-отчёт и сохраняем как артефакт
      - name: Generate Allure Report
        if: always()  # Отчёт создаётся, даже если тесты упали
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: target/allure-report