name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
  workflow_dispatch:  # Для ручного запуска

jobs:
  compile:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile project
        run: mvn compile

  test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps
          npx playwright install chromium firefox webkit

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: target/site/allure-maven-plugin