name: Run Automated Tests with Playwright

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Ручной запуск через UI GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Загрузка кода
      - uses: actions/checkout@v4

      # Шаг 2: Установка Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Шаг 3: Установка Node.js (требуется для Playwright)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Шаг 4: Установка браузеров Playwright
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps
          npx playwright install chromium

      # Шаг 5: Запуск тестов через Maven
      - name: Run Tests
        run: mvn clean test

      # Шаг 6: Генерация Allure-отчёта
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      # Шаг 7: Загрузка отчёта как артефакта
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: target/allure-report

      # (Опционально) Загрузка скриншотов/видео от Playwright
      - name: Upload Playwright traces
        uses: actions/upload-artifact@v3
        if: failure()  # Только при падении тестов
        with:
          name: playwright-trace
          path: |
            target/playwright-traces/
            target/screenshots/